version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: property_search
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./property-search-api/migrations:/docker-entrypoint-initdb.d

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  api:
    build: ./property-search-api
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/property_search
      - REDIS_URL=redis://redis:6379
      - EMBEDDING_SERVICE_URL=http://embedding-service:8001
    depends_on:
      - postgres
      - redis
    volumes:
      - ./property-search-api:/app
      - /app/node_modules

  embedding-service:
    build: ./property-embedding-service
    ports:
      - "8001:8001"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    volumes:
      - ./property-embedding-service:/app

  frontend:
    build: ./property-search-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_PUBLIC_MAPTILER_KEY=your_maptiler_key
    depends_on:
      - api
    volumes:
      - ./property-search-frontend:/app
      - /app/node_modules

volumes:
  postgres_data:
  redis_data:
